### ISSUE TITLE
Source Link

### ISSUE THREAD

**Issue by ds5678** [Speykious/NativeFileDialogs.NET#4]
I notice that the GitHub source link isn't working as expected (#1). I think it's because we need the RepositoryUrl defined.

https://github.com/dotnet/sourcelink
https://github.com/dotnet/sourcelink/blob/main/docs/README.md

About the source link package reference, if we bump to .NET 8, that can be removed because the .NET 8 SDK automatically includes source link information when appropriate.

**Comment by Speykious** [comment]
I should bump to .NET 8 then?

I hope nobody using this is stuck on .NET 6 or something xD

**Comment by ds5678** [comment]
Sounds good to me

**Comment by ds5678** [comment]
I think caf98b92f7b342bde634b18aba5180d24775c311 should address this.

**Comment by ds5678** [comment]
I think we might need one more thing for this, because I've been noticing that source link still isn't working on my other repositories.
```
<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
```
Possibly also this:
```
<PublishRepositoryUrl>true</PublishRepositoryUrl>
```
Reference: https://mitchelsellers.com/blog/article/net-5-deterministic-builds-source-linking

**Comment by Speykious** [comment]
> This simply ensures that the environment knows this was a build from a CI system.

I'm not using any CI to publish NativeFileDialogs.Net packages right now. I don't think I should be adding this.

But `<PublishRepositoryUrl>true</PublishRepositoryUrl>` seems like the right thing to add. Is there a way you can test this without me publishing a new package again?

**Comment by ds5678** [comment]
> I'm not using any CI to publish NativeFileDialogs.Net packages right now. I don't think I should be adding this.

It's a badly named attribute. It just makes the build deterministic.
