### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by ds5678** [Speykious/NativeFileDialogs.NET#5]
After the "mission-critical" issues are addressed, are you okay with me setting up some name cleaning in the generator project?

Example:
```cs
public enum NfdresultT
{
    NFD_ERROR = 0,
    NFD_OKAY = 1,
    NFD_CANCEL = 2
}
public enum NfdResult
{
    Error = 0,
    Okay= 1,
    Cancel = 2
}
```

**Comment by Speykious** [comment]
Sure

**Comment by ds5678** [comment]
Is it still okay if I do this?

**Comment by Speykious** [comment]
I wonder. It's a breaking change. Do I want to go to 2.0.0 already? 🤔

**Comment by Speykious** [comment]
Nvm, the string marshalling fix was already a breaking change and I didn't up the version correctly lol

So yeah it's fine :)
